/*
 * shell-sensor-addresses.h
 *
 *  Created on: 2014-03-17
 *      Author: francispapineau
 */

#ifndef SHELL_SENSOR_ADDRESSES_H_
#define SHELL_SENSOR_ADDRESSES_H_

#define LOCAL_ADDRESS					0x00
#define LIGHT_SENSOR_ADDRESS			0x00
#define HUMIDITY_SENSOR_ADDRESS			0x00
#define TEMPERATURE_SENSOR_ADDRESS		0x00
#define PRESSURE_SENSOR_ADDRESS			0x00
#define ALTITUDE_SENSOR_ADDRESS			0x00
#define BATTERY_SENSOR_ADDRESS			0x00

const unsigned char device_addresses[] = {LOCAL_ADDRESS, LIGHT_SENSOR_ADDRESS,
										HUMIDITY_SENSOR_ADDRESS, TEMPERATURE_SENSOR_ADDRESS,
										PRESSURE_SENSOR_ADDRESS, ALTITUDE_SENSOR_ADDRESS,
										BATTERY_SENSOR_ADDRESS};


#endif /* SHELL_SENSOR_ADDRESSES_H_ */
